# spring.application.name=motocatalog
# logging.level.root=debug
# logging.file.name=app.log
# logging.logback.rollingpolicy.max-file-size = 1MB

# logging:
#   level:
#     root: debug
#   file:
#     name: app.log
#   logback:
#     rollingpolicy:
#       max-file-size: 1MB

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/motocatalogdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: develop
        password: develop
    jpa:
        hibernate:
            ddl-auto: create-drop
    sql:
        init:
            mode: always
            encoding: UTF-8
            # enabled: true

mybatis:
    configuration:
        map-underscore-to-camel-case: true